### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by AbdullahAli** [appbaseio/mirage#13]
Whenever I try to connect, I get the following error, please help

![screen shot 2016-10-06 at 15 06 01](https://cloud.githubusercontent.com/assets/1620134/19155103/1c92b2b4-8bd5-11e6-8225-e11f42a68ed5.png)

**Comment by siddharthlatest** [comment]
@AbdullahAli will look into this.

**Comment by farhan687** [comment]
@AbdullahAli Did you change your elasticsearch config file?

For example it should be something like this:

```yml
http.port: 9200
 http.cors.allow-origin: "*"
 http.cors.enabled: true
 http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization
 http.cors.allow-credentials: true
```
