### ISSUE TITLE
Chrome extension does not give option to create query

### ISSUE THREAD

**Issue by AbdullahAli** [appbaseio/mirage#15]
The chrome extension does not allow me to create a query, after selecting the index, nothing appears under it:

![screen shot 2016-10-06 at 15 24 36](https://cloud.githubusercontent.com/assets/1620134/19155845/d1cf9bfe-8bd7-11e6-920e-b66b4edde960.png)

**Comment by farhan687** [comment]
Does it happen with pre loaded queries?

**Comment by AbdullahAli** [comment]
no, preloaded looks okay, but it does not allow me to change the connection at the top, so I can't use it:

![screen shot 2016-10-06 at 16 05 34](https://cloud.githubusercontent.com/assets/1620134/19157509/6f4d5bb4-8bdd-11e6-9672-112a2bd8d0a7.png)

**Comment by farhan687** [comment]
You can use 'disconnect button' on the right side top corner and edit it over there.
and one more thing

Did you change your elasticsearch config file?

For example it should be something like this:

```yml
http.port: 9200
 http.cors.allow-origin: "*"
 http.cors.enabled: true
 http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization
 http.cors.allow-credentials: true
```
