### ISSUE TITLE
Chrome extension doesn't work against local unauthenticated instance

### ISSUE THREAD

**Issue by tjrobinson** [appbaseio/mirage#18]
I've installed the latest Chrome extension from the Chrome store.

When I connect to `http://127.0.0.1:9200` or `http://localhost:9200` it fails with:

```
Authentication Error

It looks like your app name, username, password combination doesn't match.
Check your url and appname and then connect it again.
```

I've added this to my elasticsearch.yml file and restarted before doing the above:

```
http.cors.allow-origin: "http://127.0.0.1:9200"
http.cors.enabled: true
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization
http.cors.allow-credentials: true
```

**Comment by tjrobinson** [comment]
Looking in the Chrome console I see that:

```
username: "127.0.0.1", password: "9200"
```

**Comment by farhan687** [comment]
Hey @tjrobinson It looks like CORS error, your allow origin should be like this
```yml
http.cors.allow-origin: "*"
```

Steps:
1) Stop elasticsearch
2) update config
Es config:
```yml
http.cors.allow-origin: "*"
http.cors.enabled: true
http.cors.allow-headers : "X-Requested-With, X-Auth-Token, Content-Type, Content-Length, Authorization"
http.cors.allow-methods: "OPTIONS, HEAD, GET, POST, PUT, DELETE"
http.cors.allow-credentials: true
```
3) start elasticsearch

4) Open console and try to make a request.
```yml
var xhr = new XMLHttpRequest();
xhr.open('POST', 'http://localhost:9200/_search', true);
xhr.withCredentials = true;
xhr.setRequestHeader('Content-Type', 'application/json');
xhr.setRequestHeader('Authorization', 'Basic ' + btoa('test:test'));
xhr.send('{"query":{"match_all":{}}}');
```

If it's response status is 200 then try with mirage, mirage should work after that. If you are facing any error in request post the error log over here or checkout [CORS issue for elasticsearch](https://github.com/elastic/elasticsearch/issues/9063)

**Comment by tjrobinson** [comment]
I've done that and Mirage is still giving the same error.

Using the Chrome console I get this:

![image](https://cloud.githubusercontent.com/assets/925311/19301940/f4111266-9059-11e6-9867-e55b84386e4e.png)

I think the problem is that we have no authentiction set up on our ES instances, but Mirage and your script above send credentials?

**Comment by farhan687** [comment]
I just confirmed, mirage chrome extension is working fine with local connection.
and yes it was my mistake in above steps. 

Es config should be:

```yml
http.cors.enabled: true
http.cors.allow-origin: "/.*/"
http.cors.allow-credentials: true
http.cors.allow-headers: "Authorization, X-Requested-With, Content-Type, Content-Length"
```

and still if you see the issue, please provide detail of es version.
